### PR TITLE
Added ZW080 (Siren Gen5)

### PR DESCRIPTION
**Pull request by SergeRegoor**

### CODE REVIEW

**Comment by FreeFrags** [comment]
Not sure if it would help you implement more features for the siren, as far as i can see you added the most important feature :)  

But i found the engineering spec for the siren which explains the different features:
[http://www.vesternet.com/downloads/dl/file/id/426/product/1311/z_wave_aeon_labs_siren_engineering_specification.pdf](url)

**Comment by SergeRegoor** [comment]
Which feature would you like to see added?

**Comment by FreeFrags** [comment]
I wasnt referring to any feature in particular i was just trying to help out and share what i found out so far i found the document i linked and thought it might help you.

**Comment by SergeRegoor** [comment]
Ah, sorry :-)
Thanks for the link. Doesn't contain new information compared to the pepper database, which I used for the driver.

**Comment by FreeFrags** [comment]
not a problem hope it gets merged soon

**Comment by FreeFrags** [comment]
I can confirm this PR works :) thanks for your work. Installed it through the command line and it works well.

**Pull request merged**
