### PR TITLE
Add support for Home Energy Clamp ZW095C

### PR DESCRIPTION
**Pull request by specialcircumstances**
Hope I'm doing this right....

### CODE REVIEW

**Comment by specialcircumstances** [comment]
Hi @RobinBol - hope this is suitable. Have incorporated voltage and current measurements also.

**Comment by specialcircumstances** [comment]
Not quite sure what you mean? I have one of these, and wanted it to work with Homey... so...

image
image
image
image
image

Doesn't appear to crash and discovers the device OK.
I think there is a user in the related Issue thread also testing.

**Comment by specialcircumstances** [comment]
@RobinBol - is there anything else you need me to do here?

**Comment by RobinBol** [comment]
Just one thing, where did you get the icon and image? The image looks like the aeotec keyfob. Maybe use the icon below and update the image to one of the home energy clamp.

[home_meter_icon.svg.zip](https://github.com/athombv/com.aeotec/files/1632835/home_meter_icon.svg.zip)

**Comment by specialcircumstances** [comment]
Ah.... to be honest, I was a bit lazy on that and just grabbed something similar. Is there a handy little app for creating/editing the svg you can recommend?

**Comment by RobinBol** [comment]
Ah, the zip file that I appended contains a .svg file which you can use (this was created by one of our designers). If you want to request further icons in the future, you can place your requests here: https://github.com/athombv/homey-vectors-public/issues

**Comment by specialcircumstances** [comment]
@RobinBol - how's that?

**Comment by RobinBol** [comment]
@specialcircumstances I've got feedback from the app update that the value of 'current' is not refreshing, values for clamp 1 are also not updating (only initial values), clamp 2 and clamp 3 are not detected/displayed at all. Is this something you recognize?

**Comment by specialcircumstances** [comment]
@RobinBol Thanks for the feedback. Happy to look into this. 
First off, I only have a single clamp version and while I made a guess about how to read a three clamp version this appeared to break discovery for the 1 clamp version, therefore at present (unless we can find a guinea pig to test for me) the app can only support the 1 clamp version. Happy to work with the person reporting the image to try and build in the additional logic for the 3 clamp version if they can spare the time.
With regards to Clamp 01 only reporting on the initial reading, this is down to the configuration (which may adjusted using the available parameters). By default the parameters set only the Whole HEM to report regularly, because for a 1 clamp version the result is much the same. The reports can easily be set to include the reports for Clamp 01, I think in the Issue related to this I've mentioned them.

**Comment by Phearz** [comment]
Is any continuation planned for this ? @specialcircumstances still noone who can help you test this ? you still looking for a pig ?

**Pull request merged**
