### PR TITLE
fix ZW075 not updating state on startup

### PR DESCRIPTION
**Pull request by caseda**
also the GET's "Scale" of measure and meter power were swapped.

### CODE REVIEW

**Comment by caseda** [comment]
Whoops thought i added that, but apparently got distracted or something. added now :)

**Comment by RobinBol** [comment]
Seems like you also commit changes for ZW111!

**Comment by caseda** [comment]
yup, forget to uncheck that (undone) driver when syncing 😊 already fixing it

**Comment by caseda** [comment]
not changes though, new supported device :p

**Pull request merged**
