### PR TITLE
ZW095-C Home Energy Meter - Three Phase

### PR DESCRIPTION
**Pull request by Precisionsflyg**
Got all three clamps working with Homey.
Added the Gen 5 Three Clamp as a new device in the same driver as Gen
2.
Added the clamps as more nodes in multiChannelNodes.
Updated the report values and intervals.
Sends Power (Watts) every 15 seconds, sends voltage and current (Volts
and Amps) every 60 seconds and accumulated power (kWh) every 5 minutes
(300 seconds).
Added a flow action to reset the accumulated kWh in the meter, since I
bought mine used…

Report values from:
https://products.z-wavealliance.org/ProductManual/File?folder=&filename=
Manuals/2046/Home%20Energy%20Meter%20Gen5%20manual.pdf

### CODE REVIEW

**Comment by Precisionsflyg** [comment]
Seems I F'd things up on the first commit. Committed without an email.
Can that be fixed?

I have tested the code on my Homey with a Home Energy Meter Gen 5, with three clamps. Everything seems to work.

Behavior will need to be checked when adding a HEM with one or two clamps. Will it add three clamps nonetheless, forcing the user to delete the extras, or will it simply crash and burn?

**Comment by RobinBol** [comment]
@Precisionsflyg thanks for your PR! I have one request, generally we have one driver per device, so it is best to separate the driver into two drivers (one Gen2, one Gen5).

**Comment by Precisionsflyg** [comment]
Normally I would agree with you, and the first version I tried was done that way. But it might get a bit confusing when someone wants to add it to the controller, and sees two identical icons and the names are truncated to the same name. You have to keep the pointer over the name for a second or two before the name is expanded.
I think you would also need to add the Meter Reset action code twice, once for each device (and maintain the code in two places).

Not much of a problem to do, just my 2 cents... ;-)

**Comment by RobinBol** [comment]
I understand, it adds code duplication, but for now it is best as the app store page is also a landing page for people looking for devices that are supported by Homey, hence it is best to be as specific as possible (gen2 vs gen5), the names will be fully visible in the app store by the way!

**Comment by jolny** [comment]
@Precisionsflyg how's this going? :)

**Comment by Precisionsflyg** [comment]
@jolny I've had too little time left for programming, I'm installing a PV-system on my roof.
Hopefully I'll get a free evening that I can spend on this real soon!

**Comment by specialcircumstances** [comment]
Hey all, not been here for a while, but saw a notification on this.

I think "WE" have an issue here. When I was putting together the original for a one clamp version, I attempted to include the three clamp support also, and from what I can see you've used the same logic. The problem is that during discovery/pairing, if you have the ONE clamp version and the THREE clamp code Homey fails to pair.

I don't know how to make optional/conditional statements in the JSON (is that even possible) - so I guess it would need some more advanced logic in the js to deal with it?

Any ideas? As is, I believe the code would break the support for the one clamp version.

**Comment by RobinBol** [comment]
I think this has become a duplicate of https://github.com/athombv/com.aeotec/pull/110. Since that seems to be the most recent/complete pull request I will close this one for the time being. Please let me know if that should not happen.

**Pull request closed without merging**
