### PR TITLE
Changed logic for capability 'locked' for Garage door controller ZW062

### PR DESCRIPTION
**Pull request by yhaugom**
I am new to Homey apps and javascript/JSON, so I could be wrong, but I have tested this on my homey with my garage door controller, and it seems to do it correctly. I always got the opposite state for my garage door both in Homey app and in HomeKit "Home" app. But not any more.

### CODE REVIEW

**Comment by RobinBol** [comment]
Hm, that might be the case. I am a bit hesitant to merge this PR though, since it will break/invert all the Flows users have currently created with the device. Since it is a garage door controller I think it should not invert it's behavior overnight.

**Comment by RobinBol** [comment]
That is a good idea indeed, @yhaugom if you could alter your PR in such a way that it exposes a setting to the user which will flip the locked state, that would be great!

**Comment by yhaugom** [comment]
Didn't have the time yet. I will try to find some soon.

**Comment by yhaugom** [comment]
This is most likely an error on my behalf. Was not able to test it, so it was kind of abandoned. Sorry for that.
Not skilled at JS.
I will have a look soon. I can see where it fails from the error attached.
Thanks.
Yngve

10. mai 2018 kl. 16:25 skrev ndit <notifications@github.com<mailto:notifications@github.com>>:


I just tried this pull request, but was not able to make it work.

got this error when trying to run it from the cli-console.

com.aeotec running...
/drivers/ZW062/driver.js:19
try {
^

SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:607:28)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at /manager/drivers.js:1:1087
at Array.forEach ()
at clientDriverInit (/manager/drivers.js:1:957)
at Homey.ready (/manager/drivers.js:1:305)
at /homey.js:1:1145
at Array.forEach ()
at Object. (/homey.js:1:1123)
at emitNone (events.js:106:13)
at Object.emit (events.js:208:7)
at /index.js:1:2567
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)

--- INFO: com.aeotec has been killed ---

Bare in mind, I'm not framilar with homey development, and not a capable java programmer. So could be something i don't understand.
But i cloned the git and fetched this pull request. Then ran it with (on the old athom SDK) athom project --run

**Comment by ndit-dev** [comment]
Thank you, I'll be happy to test the code if needed.

**PS** det var ett raskt svar ;)

**Comment by johnniemalm** [comment]
no update on this ? its a bit old problem ?

**Comment by joakim93** [comment]
For me it behaves kind of both ways now the door is closed and it shows locked but sometimes more often it is closed and shows unlocked

**Comment by Abarth695** [comment]
This is so confusing and can cause massive home security issues if not fixed
The latest update added controller fro Australia thank you
But in both Homey and Apple HomeKit it shows doors open when they are actually closed and doors closed when they are open
This also applies to your flows when programming you have to put in the opposite to what you want
To say oh well we don’t want to change it for all the people who may have it previously is totally unacceptable 
At an instant if not thinking or another family memeber seeing it is open on the app and then goes to close it but then actually opens it is asking for danger
Please fix this ASAP
THANKS

**Comment by yhaugom** [comment]
This is now flipped in the main branch elsewhere.

**Comment by yhaugom** [comment]
No, I dont think they added a setting. But they changed the logic for the open/closed status in the master branch. It has not been published to the app store I think, but the change I requested was included here: https://github.com/athombv/com.aeotec/commit/8e4c0af83f3f0a8be2a83a1e35a7049611337b99

Problem with that is if someone has a flow like myself; If my garage door is kept open for 6 minutes it automatically closes. 
That means, if the app is auto updated, and the logic is switched, the garage door will open 6 minutes later. That is why it was suggested to add a setting to manually flip the logic for existing devices, but make it right for new devices.

**Pull request closed without merging**
