### PR TITLE
ZW116 and ZW139 fixed

### PR DESCRIPTION
**Pull request by jolny**
ZW116 and ZW139 were both in the product ID for ZW139. ZW116 has energy meter while ZW139 does not, so I split them up into two separate devices with their corresponding device IDs and capabilities.

### CODE REVIEW

**Comment by RobinBol** [comment]
Hi, thanks for your contribution! Your PR looks great, did you also test the ZW139 with this PR (since we don't have that device in our office, I can't test it momentarily)? And did you verify that the settings of the ZW116 and ZW139 are identical (also in terms of size, signed, etc)?

**Comment by jolny** [comment]
I have not tested it. But at the moment, the zw139 does not work at all,
while zw116 most likely does :-)
We may be able to test 139 some day this week, if you need us to.
Besides power metering, I'm sure they are the same. There may be some
differences in the parameters available, but I'm not sure whether the
existing parameters are completely correct either,  as there appeared to be
some differences in the manual at a quick glance.
I can look at the parameters some time this week.


Den 20 nov 2017 4:12 em skrev "Robin Bolscher" <notifications@github.com>:

Hi, thanks for your contribution! Your PR looks great, did you also test
the ZW139 with this PR (since we don't have that device in our office, I
can't test it momentarily)? And did you verify that the settings of the
ZW116 and ZW139 are identical (also in terms of size, signed, etc)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/com.aeotec/pull/81#issuecomment-345724692>, or mute
the thread

**Comment by jolny** [comment]
Oh right, I might add: a customer of ours could include the ZW139 successfully but was met by this message, which is why I looked over the code in the first place:
pastedgraphic-1

**Comment by RobinBol** [comment]
Ok, thanks for the clarification. Please let me know if you've come around to testing the ZW139, I am quite opposed to releasing 'untested' code to many of our users, as you will understand:)

**Comment by jolny** [comment]
Yes, I'm going to make another commit if I find there is differences between the device parameters, and I'll tell you when we've tested the ZW139. Should be done no later than next week (I'm working at automating the work-flow with a script so will do that first). :)

**Comment by RobinBol** [comment]
Ok great! By the way, if you are looking at making such a tool, take a look here (https://github.com/athombv/zwave-generator), to prevent re-inventing the wheel:)

**Comment by jolny** [comment]
Hi again!
A customer tested ZW116, and I just tested ZW139, so I can confirm they both work as they should now :+1:

**Pull request merged**
