### PR TITLE
Added Product Type ID for AUS/NZ devices

### PR DESCRIPTION
**Pull request by danone1973**
Add Product ID for AUS/NZ devices for the following:

- Nano dimmer ZW111
- Door/Window Sensor 6 ZW112
- Nano single switch ZW116
- Range Extender 6 (z-wave plus) ZW117
- Wallmote Quad ZW130

I did test it thoroughly.

### CODE REVIEW

**Comment by RobinBol** [comment]
I don't understand, you added 5 files to the root of the folder? No changes in `app.json`, no drivers added, this doesn't work. Maybe you are missing some commits?

**Comment by danone1973** [comment]
@RobinBol I am sorry, new on Github and first time with a commit. That's all I had to change, added a product ID on each of the 5 files. No need to add any drivers as they all the same regardless of the z-wave frequency.

**Comment by RobinBol** [comment]
Ok, well the changes you committed have absolutely no effect on the functionality of the app. I suggest (if you want to start contributing to Homey Apps) to read the [contributing guidelines](https://github.com/athombv/com.aeotec/blob/master/CONTRIBUTING.md) and the [Homey Apps documentation](https://developer.athom.com/docs/apps) (in this case [SDKv1](https://apps.developer.athom.com/v1/library.1.html)).

**Comment by danone1973** [comment]
No problems mate.

**Comment by danone1973** [comment]
So why you did not add the Product type Id's for Australian frequencies in the latest commit mate? @RobinBol Ignoring us the rest of the world?

**Comment by RobinBol** [comment]
Not al all, it is just, as I said I could not accept your PR. Since it was closed I could not see/missed it when preparing the app for release. If you want these product ids to be implemented in the app it is best to open an issue with information about the devices and the product ids you'd like to add.

**Pull request closed without merging**
