### PR TITLE
add support MultiSensor 4-in-1 Gen5 (ZW074)

### PR DESCRIPTION
**Pull request by caseda**
[UNTESTED] But it's a standard device, so should work properly

### CODE REVIEW

**Comment by RobinBol** [comment]
It seems not to be sold anymore (so we can't buy to test), unless someone with this device can test it I can not approve it.

**Comment by briis** [comment]
It is very much still sold. Here is just one place you can buy it: http://www.vesternet.com/z-wave-aeon-labs-multisensor-gen5 
I really hope you can do this as all my motion sensors are this kind.

**Comment by RobinBol** [comment]
@briis you could of course already download the app from https://github.com/caseda/com.aeotec/tree/zw074-updated and upload it to your Homey to test with the device. If it works properly I might release it in the app store soon.

**Comment by caseda** [comment]
closing this PR since it's an old version of the app and driver

**Pull request closed without merging**
