### PR TITLE
Support latest athom-cli and split out HEM to three generations

### PR DESCRIPTION
**Pull request by specialcircumstances**
Restructured support for Home Energy Meters, one device per generation (G1, G2 & G5).
Support is still just for single clamp.
Added reset meter flow action from three clamp fork.
Tidy up here and there.
Will require HEMs to be re-paired.

Rewrote all parameter IDs across all devices to be text rather than integer, app will now validate with latest athom cli. Suggest some additional validation would be wise for more complex application which combine their parameters, although I think I've caught most of these (e.g. RGB LED drivers).

### CODE REVIEW

**Comment by RobinBol** [comment]
Thanks for your contribution! As you know this is really large PR with a lot of impact (on all drivers), so it will take time to review and test (besides, the app should actually be re-written to sdkv2).

**Comment by specialcircumstances** [comment]
@RobinBol - Yes, sorry, but rewrite to SDKv2 is beyond me at the moment. Let me know when work starts and I'll happily do the bits for the HEM. 
Most of the "wider" updates are just converting the text from 1: to "1":  in the JSON. There are a couple of combined/computed parameters, they should be checked more closely. As you'd need to do this for SDKv2 anyway, I guess it's not wasted effort though.

**Comment by specialcircumstances** [comment]
@RobinBol @MatthewWaanders - I'm wondering if now that that sdkv2, I should look again at this? Also, I'm wondering if there is a way to use Driver.onMapDeviceClass() to handle "the three clamp issue" ?
I'll have to rebase, so I think perhaps I should Close this request and start again from scratch... Don't want to duplicate effort though - so if this is already in hand elsewhere, let me know!!

**Comment by MatthewWaanders** [comment]
I'm thankful for your contribution but unable to merge this PR as it would not be compatible with the app as it is now. Due to large changes to the Aeotec application when it was updated to the Apps SDK2 and MeshDriver instead of the older ZwaveDriver the structure of the app has largely changed.

In your specific case, feel free to rebase and rework it as you proposed above. I'd love to review it when it's done!

**Comment by specialcircumstances** [comment]
@MatthewWaanders - totally agree :)

**Pull request closed without merging**
